name: the_walking_pet
description: A new Flutter project.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: 11.1.0
  socket_io_client: ^2.0.0
  rxdart: ^0.28.0
  json_serializable: ^6.8.0
  flutter_map_tile_caching: ^9.0.0-dev.5
  deepcopy: ^1.1.2
  geodesy: ^0.10.2
  flutter_local_notifications: ^18.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
