
import 'package:the_walking_pet/entities/Race.dart';

class Constants {
  static List<Race> raceList = [
  Race(name: "", description: "", image: "", id: 0),
  Race(
    id: 1,
    name: "Labrador Retriever", 
    description: "El Labrador Retriever es una raza amistosa, activa y muy inteligente, ideal como mascota familiar y perro de trabajo.",
    image: "assets/images/Labrador_Retriever.jpg",
  ),
  Race(
    id: 2,
    name: "Bulldog Francés", 
    description: "El Bulldog Francés es pequeño pero robusto, con una personalidad vivaz y afable. Es conocido por ser una compañía leal y afectuosa.",
    image: "assets/images/French-Bulldog.jpg",
  ),
  Race(
    id: 3,
    name: "Pastor Alemán", 
    description: "El Pastor Alemán es un perro valiente, leal y muy inteligente, comúnmente utilizado como perro de trabajo en tareas de seguridad y rescate.",
    image: "assets/images/pastor_aleman.jpg",
  ),
  Race(
    id: 4,
    name: "Golden Retriever", 
    description: "El Golden Retriever es un perro amigable, confiable y amable, con un excelente temperamento, perfecto como mascota familiar.",
    image: "assets/images/golden_retriever.jpg",
  ),
  Race(
    id: 5,
    name: "Beagle", 
    description: "El Beagle es un perro curioso, enérgico y con un gran sentido del olfato, comúnmente utilizado para la caza menor.",
    image: "assets/images/beagle.jpg",
  ),
  Race(
    id: 6,
    name: "Poodle", 
    description: "El Poodle es un perro muy inteligente, con un temperamento alegre y juguetón. Es una raza fácil de entrenar y adaptarse a distintas situaciones.",
    image: "assets/images/poodle.jpg",
  ),
  Race(
    id: 7,
    name: "Chihuahua", 
    description: "El Chihuahua es una de las razas más pequeñas del mundo, con una personalidad valiente y confiada, conocido por su lealtad a sus dueños.",
    image: "assets/images/chiguahua.jpg",
  ),
  Race(
    id: 8,
    name: "Rottweiler", 
    description: "El Rottweiler es un perro robusto, seguro de sí mismo y leal, con un instinto protector fuerte, ideal como perro guardián.",
    image: "assets/images/rottweiler.jpg",
  ),
  Race(
    id: 9,
    name: "Dachshund", 
    description: "El Dachshund es un perro pequeño pero valiente, conocido por su cuerpo alargado y su actitud curiosa, enérgica y tenaz.",
    image: "assets/images/Dachshund.jpg",
  ),
  Race(
    id: 10,
    name: "Boxer", 
    description: "El Boxer es un perro leal, enérgico y con un carácter amigable. Son muy activos y se llevan bien con los niños, lo que los hace excelentes perros familiares.",
    image: "assets/images/boxer.jpg",
  ),
  Race(
    id: 11,
    name: "Siberian Husky",
    description: "El Siberian Husky es un perro enérgico, amigable y muy sociable, conocido por su resistencia y habilidad para tirar de trineos.",
    image: "assets/images/siberian_husky.png",
  ),
  Race(
    id: 12,
    name: "Shih Tzu",
    description: "El Shih Tzu es un perro pequeño y cariñoso, con un pelaje lujoso y una personalidad amigable, ideal como compañero doméstico.",
    image: "assets/images/shih_tzu.jpg",
  ),
  Race(
    id: 13,
    name: "Doberman",
    description: "El Doberman es un perro elegante, inteligente y muy leal, conocido por su velocidad y agilidad, ideal como perro guardián.",
    image: "assets/images/doberman.jpg",
  ),
  Race(
    id: 14,
    name: "Corgi Galés",
    description: "El Corgi Galés es un perro de tamaño pequeño pero robusto, conocido por su inteligencia, afecto y habilidad como perro pastor.",
    image: "assets/images/corgi_gales.jpg",
  ),
  Race(
    id: 15,
    name: "Border Collie",
    description: "El Border Collie es una de las razas más inteligentes, altamente enérgico y excelente para tareas de pastoreo y agilidad.",
    image: "assets/images/border_collie.jpg",
  ),
  Race(
    id: 16,
    name: "Boston Terrier",
    description: "El Boston Terrier es un perro pequeño y encantador, con una personalidad amigable, juguetona y adaptable a la vida en ciudad.",
    image: "assets/images/boston_terrier.jpg",
  ),
  Race(
    id: 17,
    name: "Yorkshire Terrier",
    description: "El Yorkshire Terrier es un perro pequeño, valiente y enérgico, conocido por su pelaje sedoso y su actitud confiada.",
    image: "assets/images/yorkshire_terrier.jpg",
  ),
  Race(
    id: 18,
    name: "Akita Inu",
    description: "El Akita Inu es un perro grande, poderoso y digno, con un fuerte instinto protector y una naturaleza leal.",
    image: "assets/images/akita_inu.jpg",
  ),
  Race(
    id: 19,
    name: "Chow Chow",
    description: "El Chow Chow es un perro independiente y reservado, conocido por su distintiva lengua azul-negra y su lealtad a la familia.",
    image: "assets/images/chow_chow.jpg",
  ),
  Race(
    id: 20,
    name: "Basset Hound",
    description: "El Basset Hound es un perro tranquilo y amigable, con un excelente sentido del olfato, ideal para la caza menor.",
    image: "assets/images/basset_hound.jpg",
  ),
  Race(
    id: 21,
    name: "Cocker Spaniel",
    description: "El Cocker Spaniel es un perro tranquilo y amigable.",
    image: "assets/images/cocker.jpg",
  ),
  Race(
    id: 22,
    name: "Espectador",
    description: "",
    image: "assets/images/user.webp",
  ),
];
  static Map<String, bool> personalityList =  {
  "Ladrador": false,
  "Juguetón": true,
  "Cariñoso": true,
  "Protector": true,
  "Travieso": false,
  "Curioso": true,
  "Independiente": true,
  "Inteligente": true,
  "Sociable": true,
  "Asustadizo": false,
  "Tímido": true,
  "Enérgico": true,
  "Tranquilo": true,
  "Leal": true,
  "Valiente": true,
  "Nervioso": false,
  "Dócil": true,
  "Territorial": false,
  "Cazador": false,
  "Obediente": true,
  "Astuto": true,
  "Afable": true,
  "Resiliente": true
};
}